#!/usr/bin/env sh

# ██╗   ██╗ █████╗ ██████╗  █████╗ ██╗
# ╚██╗ ██╔╝██╔══██╗██╔══██╗██╔══██╗██║
#  ╚████╔╝ ███████║██████╔╝███████║██║
#   ╚██╔╝  ██╔══██║██╔══██╗██╔══██║██║
#    ██║   ██║  ██║██████╔╝██║  ██║██║
#    ╚═╝   ╚═╝  ╚═╝╚═════╝ ╚═╝  ╚═╝╚═╝
# https://github.com/koekeishiya/yabai

# sudo /opt/homebrew/bin/yabai --load-sa
# yabai -m signal --add event=dock_did_restart action="sudo /opt/homebrew/bin/yabai --load-sa"
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

### Variables ###
# Note: These variables are menat to by easily changed by anyone.
export external_bar_height="60"    # Height of external bar in pt                                    (usage: 24/16/any number)
export external_bar_position="top" # position of external bar                                        (usage: top/bottom/left/right)
export shadow_toggle="off"         # Determines wether window shadows are on                         (usage: on/off)
export mouse_mod="cmd"             # key that when pressed, mouse can be used to move and resize     (usage: cmd/alt/ctrl/shift)
export border_toggle="on"          # Determines wether borders for active windows are on             (usage: on/off)
export border_width="1"            # Determines the width of the active window's border              (usage: 2/5/any number)
export border_radius="11"          # radius of the active window's border                            (usage: 11/0/any number)
export opacity_toggle="off"        # Detriments wether opacity based focus is on                     (usage: on/off)
export layout="float"              # Layout of windows                                               (usage: bsp/float/stack)
export gap_width="0"               # width of window gaps                                            (usage: 17/8/any number)
export animation_duration="0"      # Window animation duration                                       (usage: 0.0/0.3/0.5)
export autoraise_toggle="off"      # turn autoraise on or off                                        (usage: on/off)

yabai -m config mouse_modifier $mouse_mod # make cmd the mouse modifier key (configued in variables)

# global settings
yabai -m config mouse_follows_focus off
yabai -m config focus_follows_mouse off
yabai -m config window_origin_display default
yabai -m config window_placement second_child
yabai -m config window_topmost off
yabai -m config window_shadow on
yabai -m config window_opacity off
yabai -m config window_opacity_duration 0.0
yabai -m config active_window_opacity 1.0
yabai -m config normal_window_opacity 0.90
yabai -m config window_border off
yabai -m config window_border_width 6
yabai -m config active_window_border_color 0xff775759
yabai -m config normal_window_border_color 0xff555555
yabai -m config insert_feedback_color 0xffd75f5f
yabai -m config split_ratio 0.50
yabai -m config auto_balance off

yabai -m config mouse_modifier $mouse_mod # make cmd the mouse modifier key (configued in variables)
### Confgure mouse usage ###
yabai -m config mouse_action2 resize # with left click - resize
yabai -m config mouse_action1 move   # with right click - move

# yabai -m config mouse_drop_action swap
yabai -m config window_animation_duration 0.0

# general space settings
yabai -m config layout bsp
### Configure window gaps ###
yabai -m config top_padding $gap_width
yabai -m config bottom_padding $gap_width
yabai -m config left_padding $gap_width
yabai -m config right_padding $gap_width
yabai -m config window_gap $gap_width
# apps to not manage (ignore)
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Microsoft Teams$" manage=off
yabai -m rule --add app="^Microsoft Teams classic$" manage=off
yabai -m rule --add app="^Microsoft Teams (work or school)$" manage=off
yabai -m rule --add app="^Archive Utility$" manage=off
yabai -m rule --add app="^FaceTime$" manage=off
yabai -m rule --add app="^Wally$" manage=off
yabai -m rule --add app="^Pika$" manage=off
yabai -m rule --add app="^balenaEtcher$" manage=off
yabai -m rule --add app="^Creative Cloud$" manage=off
yabai -m rule --add app="^Logi Options$" manage=off
yabai -m rule --add app="^Alfred Preferences$" manage=off
yabai -m rule --add app="Raycast" manage=off

echo "yabai configuration loaded.."
